<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="87166" started-at="2021-03-12T09:34:46Z" finished-at="2021-03-12T09:36:13Z">
    <groups>
      <group name="RegressionTest">
        <method signature="createOrgWithNotifyOwner.createWithNotifyOwner()[pri:0, instance:Organization.createOrgWithNotifyOwner@e25b2fe]" name="createWithNotifyOwner" class="Organization.createOrgWithNotifyOwner"/>
      </group> <!-- RegressionTest -->
    </groups>
    <test name="Default test" duration-ms="87166" started-at="2021-03-12T09:34:46Z" finished-at="2021-03-12T09:36:13Z">
      <class name="Organization.createOrgWithNotifyOwner">
        <test-method status="PASS" signature="configBeforeSuite()[pri:0, instance:Organization.createOrgWithNotifyOwner@e25b2fe]" name="configBeforeSuite" is-config="true" duration-ms="1546" started-at="2021-03-12T15:19:44Z" finished-at="2021-03-12T15:19:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBeforeSuite -->
        <test-method status="PASS" signature="configBeforeClass()[pri:0, instance:Organization.createOrgWithNotifyOwner@e25b2fe]" name="configBeforeClass" is-config="true" duration-ms="21882" started-at="2021-03-12T15:19:47Z" finished-at="2021-03-12T15:20:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBeforeClass -->
        <test-method status="PASS" signature="configBeforeMtd()[pri:0, instance:Organization.createOrgWithNotifyOwner@e25b2fe]" name="configBeforeMtd" is-config="true" duration-ms="5998" started-at="2021-03-12T15:20:09Z" finished-at="2021-03-12T15:20:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configBeforeMtd -->
        <test-method status="FAIL" signature="createWithNotifyOwner()[pri:0, instance:Organization.createOrgWithNotifyOwner@e25b2fe]" name="createWithNotifyOwner" duration-ms="47751" started-at="2021-03-12T15:20:15Z" finished-at="2021-03-12T15:21:03Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at Organization.createOrgWithNotifyOwner.createWithNotifyOwner(createOrgWithNotifyOwner.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createWithNotifyOwner -->
        <test-method status="PASS" signature="configAfterMethod()[pri:0, instance:Organization.createOrgWithNotifyOwner@e25b2fe]" name="configAfterMethod" is-config="true" duration-ms="5528" started-at="2021-03-12T15:21:04Z" finished-at="2021-03-12T15:21:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterMethod -->
        <test-method status="PASS" signature="configAfterClass()[pri:0, instance:Organization.createOrgWithNotifyOwner@e25b2fe]" name="configAfterClass" is-config="true" duration-ms="3955" started-at="2021-03-12T15:21:09Z" finished-at="2021-03-12T15:21:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterClass -->
        <test-method status="PASS" signature="configAfterSuite()[pri:0, instance:Organization.createOrgWithNotifyOwner@e25b2fe]" name="configAfterSuite" is-config="true" duration-ms="47" started-at="2021-03-12T15:21:16Z" finished-at="2021-03-12T15:21:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configAfterSuite -->
      </class> <!-- Organization.createOrgWithNotifyOwner -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
